export const metadata = {
  title: {
    absolute: "",
    default: "Next.JS Course - Cristian!",
    template: "%s | Next.JS Course - Cristian!",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
